---
- name: Installing and Configuring Web Server on target node
  # Hosts Section
  hosts: 
    - target        
  become: yes

  tasks:
    - name: Check if the service is running
      command: service httpd status
        warn=False
      register: result
      ignore_errors: yes
      when: ansible_os_family == 'RedHat'
    
    - debug:
        var: result

    - name: Stopping the apache web server service
      service:
        name: httpd
        state: stopped
        enabled: no
      when: result is succeeded
    
    - name: Removing the apache web server package
      yum:
        name: httpd
        state: absent

    - name: Removing the directories created by apache web server package
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/httpd
        - /var/www/html
        - /var/log/httpd        

